/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: PhantomXD (https://sketchfab.com/PhantomXD)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/java-442de0f1b8a54966bc16466b329105af
Title: Java
*/

import { useGLTF, Float } from '@react-three/drei'
import * as THREE from 'three'
import { useRef } from 'react';


const JavaLogo = (props: any) => {
  const group = useRef<THREE.Group>(null)
  const { nodes } = useGLTF<any>('/models/java.glb') as any;
  
  
 const gradientMaterial = new THREE.MeshStandardMaterial({
    color: new THREE.Color('#5382A1'), // Base muted teal color
    metalness: 1,                    // High metalness for reflectivity
    roughness: 0.3,                     // Moderate roughness for realism
    emissive: new THREE.Color('#416F87'), // Subtle emissive deep blue-green effect
    emissiveIntensity: 0.2,
  });

  const glowingMaterial = new THREE.MeshStandardMaterial({
    color: new THREE.Color('#FFA500'),
    emissive: new THREE.Color('#FF8800'),
    emissiveIntensity: 2.0,
    transparent: true,
    opacity: 0.8,
  });
 
  return (
    
    // <>    <EffectComposer>
    //     <Bloom luminanceThreshold={0.2} luminanceSmoothing={0.5} intensity={2.5} />
    //   </EffectComposer>
    <Float floatIntensity={0}>
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="Cube">
              <mesh
                name="Cube_0"
                castShadow
                receiveShadow
                geometry={(nodes.Cube_0 as any).geometry}
                material={gradientMaterial}
              />
            </group>
            <group name="Plane" position={[0.787, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh
                name="Plane_0"
                castShadow
                receiveShadow
                geometry={(nodes.Plane_0 as any).geometry}
                material={gradientMaterial}
              />
            </group>
            <group
              name="Plane001"
              position={[0, 0, 1.518]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={1.218}>
              <mesh
                name="Plane001_0"
                castShadow
                receiveShadow
                geometry={(nodes.Plane001_0 as any).geometry}
                material={glowingMaterial}
                morphTargetDictionary={(nodes.Plane001_0 as any).morphTargetDictionary}
                morphTargetInfluences={(nodes.Plane001_0 as any).morphTargetInfluences}
              />
            </group>
            <group
              name="Torus001"
              position={[-0.138, -0.061, -0.771]}
              rotation={[-0.14, -0.02, 0.097]}
              scale={[0.467, 0.432, 0.432]}>
              <mesh
                name="Torus001_0"
                castShadow
                receiveShadow
                geometry={(nodes.Torus001_0 as any).geometry}
                material={gradientMaterial}
              />
            </group>
            <group
              name="Torus000"
              position={[0.095, -0.029, -0.88]}
              rotation={[-0.134, -0.046, 0.098]}
              scale={[0.454, 0.419, 0.303]}>
              <mesh
                name="Torus000_0"
                castShadow
                receiveShadow
                geometry={(nodes.Torus000_0 as any).geometry}
                material={gradientMaterial}
              />
            </group>
          </group>
        </group>
      </group>
      
    </group>
    </Float>
   

  )
}

useGLTF.preload('/models/java.glb')

export default JavaLogo;